const adminPrefix = '/admin/'
const authPrefix = '/app/'

const PathConstants: { [key: string]: string } = {
    home: '/',
    publicProfile: '/profile/:identifier',
    about: '/about/',
    offer: '/offer/',
    ventureDirectory: '/directory/',
    login: '/login/',
    signUp: '/register/',
    signUpVerification: '/register/verification',
    forgotPassword: '/forgot-password/',
    confirmForgotPassword: '/confirm-forgot-password/',
    terms: '/onboarding/terms-of-use',
    personal: '/onboarding/personal-information',
    onboarding: '/onboarding/path',
    companyProfile: '/onboarding/company-profile',
    developmentStage: '/development/stage',
    developmentChallenges: '/development/challenges',
    developmentFundraising: '/development/fundraising',
    community: '/community/',
    help: '/help/',
    contactUs: '/contact/',
    adminHome: `${adminPrefix}home`,
    adminVideos: `${adminPrefix}videos`,
    adminVideo: `${adminPrefix}videos/:id`,
    adminVentures: `${adminPrefix}ventures`,
    adminTemplates: `${adminPrefix}templates`,
    adminTemplate: `${adminPrefix}templates/:id`,
    adminArticles: `${adminPrefix}articles`,
    adminCreateArticles: `${adminPrefix}articles/create`,
    adminEvents: `${adminPrefix}events`,
    adminFunding: `${adminPrefix}funding-opportunities`,
    adminSubmissions: `${adminPrefix}submissions`,
    dashboard: `${authPrefix}dashboard`,
    tasks: `${authPrefix}tasks`,
    resources: `${authPrefix}resources`,
    videos: `${authPrefix}resources/video/:id`,
    templates: `${authPrefix}resources/template/:id`,
    articles: `${authPrefix}resources/article/:id`,
    settings: `${authPrefix}settings`,
    teamPage: `${authPrefix}team-page`,
    companyEditPage: `${authPrefix}company-edit-page`,
    privateViewUpdate: `${authPrefix}private-view-update`,
    publicCompanyView: `${authPrefix}public-company-view`,
}

export default PathConstants