const adminPrefix = '/admin/'

const PathConstants: { [key: string]: string } = {
    home: '/',
    about: '/about/',
    login: '/login/',
    signUp: '/register/',
    signUpVerification: '/register/verification',
    forgotPassword: '/forgot-password/',
    confirmForgotPassword: '/confirm-forgot-password/',
    terms: '/onboarding/terms-of-use',
    personal: '/onboarding/personal-information',
    onboarding: '/onboarding/path',
    companyProfile: '/onboarding/company-profile',
    developmentStage: '/development/stage',
    developmentChallenges: '/development/challenges',
    developmentFundraising: '/development/fundraising',
    dashboard: '/dashboard/',
    resources: '/resources/',
    community: '/community/',
    help: '/help/',
    contactUs: '/contact/',
    adminHome: `${adminPrefix}home`,
    adminVideos: `${adminPrefix}videos`,
    adminVideo: `${adminPrefix}videos/:id`,
    adminVentures: `${adminPrefix}ventures`,
    adminTemplates: `${adminPrefix}templates`,
    adminTemplate: `${adminPrefix}templates/:id`,
    adminArticles: `${adminPrefix}articles`,
    adminCreateArticles: `${adminPrefix}articles/create`,
    adminEvents: `${adminPrefix}events`,
    adminFunding: `${adminPrefix}fundingOpportunuties`,
    adminSubmissions: `${adminPrefix}submissions`,
}

export default PathConstants